### ISSUE TITLE
echoing Current View

### ISSUE THREAD

**Issue by bryhal** [lonnieezell/Ocular-Template-Library#14]
On line 238 of the library file, is that an oops? I'm new with Codeigniter, took a bit to figure that out, it displayed at the top of every page

**Comment by lonnieezell** [comment]
You are correct. That would be a big oops! :) Sorry to have caused any headaches, but you can safely delete that line.

FYI - Version 3.0 is just about out, though it changes things to a PHP5-only static class. I wouldn't wait, though, since I have a hell of a deadline to hit this week, but I might be able to squeeze in some time to finish up the docs on it.
